// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Player struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	YearStart int32     `json:"year_start"`
	YearEnd   int32     `json:"year_end"`
	Position  string    `json:"position"`
	Height    string    `json:"height"`
	Weight    int32     `json:"weight"`
	BirthDate time.Time `json:"birth_date"`
	College   string    `json:"college"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
