// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package database

import (
	"context"
)

const getLeBronJames = `-- name: GetLeBronJames :one
SELECT id, name, year_start, year_end, position, height, weight, birth_date, college, created_at, updated_at FROM players
WHERE name LIKE '%LeBron%' LIMIT 1
`

func (q *Queries) GetLeBronJames(ctx context.Context) (Player, error) {
	row := q.db.QueryRowContext(ctx, getLeBronJames)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.YearStart,
		&i.YearEnd,
		&i.Position,
		&i.Height,
		&i.Weight,
		&i.BirthDate,
		&i.College,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayers = `-- name: GetPlayers :many
SELECT id, name, year_start, year_end, position, height, weight, birth_date, college, created_at, updated_at FROM players
LIMIT 10
`

func (q *Queries) GetPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.YearStart,
			&i.YearEnd,
			&i.Position,
			&i.Height,
			&i.Weight,
			&i.BirthDate,
			&i.College,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
