// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Player struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	YearStart sql.NullInt32  `json:"year_start"`
	YearEnd   sql.NullInt32  `json:"year_end"`
	Position  sql.NullString `json:"position"`
	Height    sql.NullString `json:"height"`
	Weight    sql.NullInt32  `json:"weight"`
	BirthDate sql.NullTime   `json:"birth_date"`
	College   sql.NullString `json:"college"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
