// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package database

import (
	"context"
)

const getLeBronJames = `-- name: GetLeBronJames :one
SELECT id, name, year_start, year_end, position, height, weight, birth_date, college, created_at, updated_at FROM players
WHERE name LIKE '%LeBron%' LIMIT 1
`

func (q *Queries) GetLeBronJames(ctx context.Context) (Player, error) {
	row := q.db.QueryRowContext(ctx, getLeBronJames)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.YearStart,
		&i.YearEnd,
		&i.Position,
		&i.Height,
		&i.Weight,
		&i.BirthDate,
		&i.College,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
